Repository icure/icure-medical-device-js-sdk, pull requests merged in 2022-10, with the labels that each got.

#40 New release
  .github/workflows/build.yml
  package.json
  src/filter/filterDsl.ts
  src/filter/hcp/HealthcareProfessionalByLabelCodeFilter.ts
  src/mappers/filter.ts
  src/mappers/healthcareProfessional.ts
  src/models/HealthcareProfessional.ts
  test/apis/data-sample-api.ts
  test/apis/subscription-apis.ts
  test/filter/hcp-filters-test.ts
  yarn.lock
Labels: SemVer.Patch

#45 Fixed RSocket Patient test
  .github/workflows/publish.yml
  test/apis/subscription-apis.ts
Labels: SemVer.Minor

#46 Improve error handling in services
  .pre-commit-config.yaml
  src/apis/AnonymousMedTechApi.ts
  src/apis/MedTechApi.ts
  src/apis/impl/AuthenticationApiImpl.ts
  src/apis/impl/CodingApiImpl.ts
  src/apis/impl/DataOwnerApiImpl.ts
  src/apis/impl/DataSampleApiImpl.ts
  src/apis/impl/HealthcareElementApiImpl.ts
  src/apis/impl/HealthcareProfessionalApiImpl.ts
  src/apis/impl/MedicalDeviceApiImpl.ts
  src/apis/impl/MessageGatewayApiImpl.ts
  src/apis/impl/NotificationApiImpl.ts
  src/apis/impl/PatientApiImpl.ts
  src/apis/impl/UserApiImpl.ts
  src/services/ErrorHandler.ts
  src/services/Sanitizer.ts
  src/services/impl/ErrorHandlerImpl.ts
  src/services/impl/SanitizerImpl.ts
  test/services/erroHandler.ts
  test/services/sanitizer.ts
  test/test-utils.ts
Labels: enhancement

#51 Feature mdt-78 regenerate lost key
  package.json
  src/apis/DataOwnerApi.ts
  src/apis/NotificationApi.ts
  src/apis/impl/DataOwnerApiImpl.ts
  src/apis/impl/NotificationApiImpl.ts
  src/filter/filterDsl.ts
  test/apis/authentication-api.ts
  test/apis/data-sample-api.ts
  test/apis/notification-api.ts
  test/apis/patient-api.ts
  test/apis/user-from-existing-patient.ts
  yarn.lock
Labels: enhancement

#53 Exposed Storage facades
  index.ts
  package.json
  src/apis/AnonymousMedTechApi.ts
  src/apis/MedTechApi.ts
  src/apis/impl/AuthenticationApiImpl.ts
  src/apis/impl/DataOwnerApiImpl.ts
  test/apis/authentication-api.ts
  test/test-utils.ts
  yarn.lock
Labels: enhancement

#54 Fixed update of MedicalDevice
  src/apis/impl/MedicalDeviceApiImpl.ts
  src/mappers/medicalDevice.ts
  test/apis/medical-device.ts
Labels: bug, patch

#52 Release 1.0.0
  .pre-commit-config.yaml
  index.ts
  package.json
  sonar-project.properties
  src/apis/AnonymousMedTechApi.ts
  src/apis/DataOwnerApi.ts
  src/apis/MedTechApi.ts
  src/apis/NotificationApi.ts
  src/apis/impl/AuthenticationApiImpl.ts
  src/apis/impl/CodingApiImpl.ts
  src/apis/impl/DataOwnerApiImpl.ts
  src/apis/impl/DataSampleApiImpl.ts
  src/apis/impl/HealthcareElementApiImpl.ts
  src/apis/impl/HealthcareProfessionalApiImpl.ts
  src/apis/impl/MedicalDeviceApiImpl.ts
  src/apis/impl/MessageGatewayApiImpl.ts
  src/apis/impl/NotificationApiImpl.ts
  src/apis/impl/PatientApiImpl.ts
  src/apis/impl/UserApiImpl.ts
  src/filter/filterDsl.ts
  src/mappers/medicalDevice.ts
  src/mappers/serviceDataSample.ts
  src/services/ErrorHandler.ts
  src/services/Sanitizer.ts
  src/services/impl/ErrorHandlerImpl.ts
  src/services/impl/SanitizerImpl.ts
  src/utils/filterUndefined.ts
  test/apis/authentication-api.ts
  test/apis/data-sample-api.ts
  test/apis/healthcare-element-api.ts
  test/apis/medical-device.ts
  test/apis/notification-api.ts
  test/apis/patient-api.ts
  test/apis/user-from-existing-patient.ts
  test/services/erroHandler.ts
  test/services/sanitizer.ts
  test/test-utils.ts
  yarn.lock
Labels: SemVer.Major

#57 Updated @icure/api
  package.json
  test/apis/authentication-api.ts
  yarn.lock
Labels: hotfix, SemVer.Patch

#56 Updated @icure/api
  package.json
  test/apis/authentication-api.ts
  yarn.lock
Labels: hotfix, SemVer.Patch
