Repository icure/icure-medical-device-js-sdk, pull requests merged in 2022-11, with the labels that each got.

#60 MDT-155 Implemented new test stack
  .github/workflows/build.yml
  .gitignore
  README.md
  package-lock.json
  package.json
  src/apis/MedTechApi.ts
  src/apis/impl/NotificationApiImpl.ts
  src/apis/impl/PatientApiImpl.ts
  src/filter/index.ts
  src/utils/equality.ts
  test/apis/authentication-api.ts
  test/apis/data-sample-api.ts
  test/apis/hcp-user.ts
  test/apis/healthcare-element-api.ts
  test/apis/medical-device.ts
  test/apis/notification-api.ts
  test/apis/patient-api.ts
  test/apis/subscription-apis.ts
  test/apis/user-api.ts
  test/apis/user-from-existing-patient.ts
  test/cleanup.ts
  test/filter/hcp-filters-test.ts
  test/filter/user-filters-test.ts
  test/test-setup-decorators.ts
  test/test-utils.ts
  test/utils/equality-utils-test.ts
  yarn.lock
Labels: enhancement, ignore-for-release

#62 Updated @icure/api
  package.json
  yarn.lock
Labels: patch

#61 Updated @icure/api
  package.json
  yarn.lock
Labels: hotfix

#64 Added loading of keyPairs when using initUserCrypto
  README.md
  package.json
  src/apis/DataOwnerApi.ts
  src/apis/MedTechApi.ts
  src/apis/impl/AuthenticationApiImpl.ts
  src/apis/impl/DataOwnerApiImpl.ts
  test/apis/authentication-api.ts
  test/apis/data-sample-api.ts
  test/apis/hcp-user.ts
  test/apis/utils/MemoryStorage.ts
  test/test-setup-decorators.ts
  test/test-utils.ts
  yarn.lock
Labels: enhancement

#65 1.1.0 release
  .github/workflows/build.yml
  .gitignore
  README.md
  package-lock.json
  package.json
  src/apis/DataOwnerApi.ts
  src/apis/MedTechApi.ts
  src/apis/UserApi.ts
  src/apis/impl/AuthenticationApiImpl.ts
  src/apis/impl/DataOwnerApiImpl.ts
  src/apis/impl/NotificationApiImpl.ts
  src/apis/impl/PatientApiImpl.ts
  src/apis/impl/UserApiImpl.ts
  src/filter/index.ts
  src/utils/equality.ts
  test/apis/authentication-api.ts
  test/apis/data-sample-api.ts
  test/apis/hcp-user.ts
  test/apis/healthcare-element-api.ts
  test/apis/medical-device.ts
  test/apis/notification-api.ts
  test/apis/patient-api.ts
  test/apis/subscription-apis.ts
  test/apis/user-api.ts
  test/apis/user-from-existing-patient.ts
  test/apis/utils/MemoryStorage.ts
  test/cleanup.ts
  test/filter/hcp-filters-test.ts
  test/filter/user-filters-test.ts
  test/test-setup-decorators.ts
  test/test-utils.ts
  test/utils/equality-utils-test.ts
  yarn.lock
Labels: SemVer.Minor

#67 Back-merge 1.1.0
  package.json
  yarn.lock
Labels: ignore-for-release

#68 Update release process to gather migration notes
  .github/release.yml
  .github/workflows/publish.yml
Labels: documentation, ignore-for-release
