Repository icure/icure-medical-device-js-sdk, pull requests merged in 2022-12, with the labels that each got.

#69 Fixed Union and Intersection filters
  package.json
  src/apis/impl/CodingApiImpl.ts
  src/filter/filterDsl.ts
  src/mappers/codeCoding.ts
  src/mappers/filter.ts
  src/models/Coding.ts
  test/apis/authentication-api.ts
  test/filter/coding-filters-tests.ts
  test/filter/data-sample-filters-tests.ts
  test/filter/hcp-filters-test.ts
  test/filter/healthcare-element-filters-tests.ts
  test/filter/medical-device-filters-tests.ts
  test/filter/notification-filters-tests.ts
  test/filter/patient-filters-test.ts
  test/filter/user-filters-test.ts
  test/test-utils.ts
  yarn.lock
Labels: bug, enhancement

#70 Unable to login using completeAuthentication
  package.json
  src/apis/AuthenticationApi.ts
  src/apis/DataOwnerApi.ts
  src/apis/MedTechApi.ts
  src/apis/impl/AuthenticationApiImpl.ts
  src/apis/impl/DataOwnerApiImpl.ts
  src/models/AuthenticationResult.ts
  test/apis/authentication-api.ts
  test/apis/user-from-existing-patient.ts
  test/test-utils.ts
  yarn.lock
Labels: hotfix, SemVer.Patch

#74 Fix/allow for samples deletions when cache is bypassed
  src/apis/impl/DataSampleApiImpl.ts
  src/utils/cachedMap.ts
  test/apis/data-sample-api.ts
  test/test-utils.ts
Labels: bug, SemVer.Patch

#75 Release 2.0.1
  src/apis/impl/DataSampleApiImpl.ts
  src/utils/cachedMap.ts
  test/apis/data-sample-api.ts
  test/test-utils.ts
Labels: SemVer.Patch
