Repository icure/icure-medical-device-js-sdk, pull requests merged in 2022-09, with the labels that each got.

#14 MDT-69, MDT-96 Added createAndInviteUser method and Message Gateway API
  .github/workflows/build.yml
  index.ts
  src/apis/AnonymousMedTechApi.ts
  src/apis/AuthenticationApi.ts
  src/apis/MessageGatewayApi.ts
  src/apis/UserApi.ts
  src/apis/impl/AuthenticationApiImpl.ts
  src/apis/impl/MessageGatewayApiImpl.ts
  src/apis/impl/PatientApiImpl.ts
  src/apis/impl/UserApiImpl.ts
  src/apis/medTechApi.ts
  src/filter/filterDsl.ts
  src/mappers/filter.ts
  src/utils/addressUtils.ts
  src/utils/messageGatewayUtils.ts
  test/apis/authentication-api.ts
  test/apis/data-sample-api.ts
  test/apis/hcp-user.ts
  test/apis/notification-api.ts
  test/apis/patient-api.ts
  test/apis/user-from-existing-patient.ts
  test/filter/user-filters-test.ts
  test/test-utils.ts
  test/utils/address-utils-test.ts
  test/utils/equality-utils-test.ts
Labels: enhancement

#17 Added specId as parameter of API builders
  .github/workflows/build.yml
  src/apis/AnonymousMedTechApi.ts
  src/apis/MessageGatewayApi.ts
  src/apis/impl/AuthenticationApiImpl.ts
  src/apis/impl/MessageGatewayApiImpl.ts
  src/apis/impl/UserApiImpl.ts
  src/apis/medTechApi.ts
  test/apis/authentication-api.ts
  test/apis/patient-api.ts
  test/apis/user-from-existing-patient.ts
  test/test-utils.ts
Labels: enhancement

#19 GitHub configuration for auto-generated release notes
  .github/release.yml
Labels: ignore-for-release

#20 GitHub actions for npm publish and release generation
  .github/workflows/publish.yml
  .github/workflows/release.yml
Labels: ignore-for-release

#18 Added autoDelegations management
  .yarnrc.yml
  src/apis/UserApi.ts
  src/apis/impl/UserApiImpl.ts
  src/mappers/user.ts
  src/models/User.ts
  test/apis/hcp-user.ts
  test/apis/user-api.ts
Labels: enhancement, SemVer.Minor

#22 MDT-77 Divide tests
  test/apis/user-api.ts
Labels: SemVer.Minor

#23 Modify Publish GitHub Action to publish only when a PR has an appropr…
  .github/release.yml
  .github/workflows/publish.yml
  .github/workflows/release.yml
Labels: SemVer.Minor

#24 Fixed action statement
  .github/workflows/publish.yml
Labels: SemVer.Minor

#25 Fixed env variables
  .github/workflows/publish.yml
  test/test-utils.ts
Labels: SemVer.Minor

#26 [REFACTOR] Introduce small changes to MSG-GTW services signature
  src/apis/MessageGatewayApi.ts
  src/apis/impl/AuthenticationApiImpl.ts
  src/apis/impl/MessageGatewayApiImpl.ts
Labels: ignore-for-release, refactoring

#21 MDT-69, MDT-102 As a doctor, I want to be able to create a user for a patient
  package.json
  src/apis/AnonymousMedTechApi.ts
  src/apis/AuthenticationApi.ts
  src/apis/DataSampleApi.ts
  src/apis/HealthcareElementApi.ts
  src/apis/MessageGatewayApi.ts
  src/apis/NotificationApi.ts
  src/apis/PatientApi.ts
  src/apis/UserApi.ts
  src/apis/impl/AuthenticationApiImpl.ts
  src/apis/impl/DataSampleApiImpl.ts
  src/apis/impl/HealthcareElementApiImpl.ts
  src/apis/impl/MessageGatewayApiImpl.ts
  src/apis/impl/NotificationApiImpl.ts
  src/apis/impl/PatientApiImpl.ts
  src/apis/impl/UserApiImpl.ts
  src/apis/medTechApi.ts
  src/filter/filterDsl.ts
  src/filter/notification/NotificationsAfterDateFilter.ts
  src/mappers/filter.ts
  src/mappers/notification.ts
  src/models/Notification.ts
  src/utils/interfaces.ts
  src/utils/msgGtwMessageFactory.ts
  test/apis/authentication-api.ts
  test/apis/data-sample-api.ts
  test/apis/healthcare-element-api.ts
  test/apis/notification-api.ts
  test/apis/user-from-existing-patient.ts
  test/mappers/notification.ts
  test/models/notification.ts
  test/test-utils.ts
  yarn.lock
Labels: enhancement

#28 Moved icure-io to icure
  .github/workflows/publish.yml
Labels: bug, ignore-for-release, hotfix

#29 Moved icure-io to icure
  .github/workflows/publish.yml
Labels: bug, ignore-for-release, hotfix

#31 Expose utils from Icc-API dependency
  index.ts
Labels: enhancement

#32 Release 0.5.1
  index.ts
  src/apis/MessageGatewayApi.ts
  src/apis/impl/AuthenticationApiImpl.ts
  src/apis/impl/MessageGatewayApiImpl.ts
Labels: SemVer.Patch

#33 Init User Crypto Service
  .github/workflows/publish.yml
  index.ts
  src/apis/AnonymousMedTechApi.ts
  src/apis/DataOwnerApi.ts
  src/apis/MessageGatewayApi.ts
  src/apis/impl/AuthenticationApiImpl.ts
  src/apis/impl/DataOwnerApiImpl.ts
  src/apis/impl/MessageGatewayApiImpl.ts
  src/apis/medTechApi.ts
  test/apis/authentication-api.ts
  test/apis/hcp-user.ts
  test/apis/user-from-existing-patient.ts
  test/test-utils.ts
Labels: enhancement, SemVer.Minor, refactoring

#35 Release v0.6.0
  .github/workflows/publish.yml
  index.ts
  src/apis/AnonymousMedTechApi.ts
  src/apis/DataOwnerApi.ts
  src/apis/MessageGatewayApi.ts
  src/apis/impl/AuthenticationApiImpl.ts
  src/apis/impl/DataOwnerApiImpl.ts
  src/apis/impl/MessageGatewayApiImpl.ts
  src/apis/medTechApi.ts
  test/apis/authentication-api.ts
  test/apis/hcp-user.ts
  test/apis/user-from-existing-patient.ts
  test/test-utils.ts
Labels: SemVer.Minor
