Repository icure/icure-medical-device-js-sdk, pull requests merged in 2023-04, with the labels that each got.

#106 Update default iCure Backend API URL
  index.ts
  src/apis/AnonymousMedTechApi.ts
  src/apis/MedTechApi.ts
  src/util.ts
  test/util.ts
Labels: hotfix, SemVer.Patch

#108 Fix Source Maps Generation Issue by upgrading WS dependencies
  .npmignore
  package.json
  tsconfig.json
  yarn.lock
Labels: hotfix, SemVer.Patch

#109 It is possible to pass just one authProcessId instead of both
  .github/workflows/build.yml
  src/apis/AnonymousMedTechApi.ts
  src/apis/AuthenticationApi.ts
  src/apis/MedTechApi.ts
  src/apis/impl/AuthenticationApiImpl.ts
  test/apis/authentication-api.ts
  test/test-utils.ts
Labels: enhancement

#110 Fixed description missing from HealthcareElement when obtained by filter
  package.json
  src/apis/impl/HealthcareElementApiImpl.ts
  test/apis/healthcare-element-api.ts
  yarn.lock
Labels: bug
