Repository icure/icure-medical-device-js-sdk, pull requests merged in 2023-01, with the labels that each got.

#78 Patch release management
  .github/workflows/publish.yml
Labels: ignore-for-release

#79 React-Native support for adding keys
  .yarnrc
  package-lock.json
  package.json
  src/apis/impl/DataOwnerApiImpl.ts
  yarn.lock
Labels: patch

#80 2.0.3
  .github/workflows/publish.yml
  .yarnrc
  package-lock.json
  package.json
  src/apis/impl/DataOwnerApiImpl.ts
  src/filter/filterDsl.ts
  src/filter/hcp/HealthcareProfessionalByNameFilter.ts
  src/mappers/filter.ts
  test/filter/hcp-filters-test.ts
  test/filter/patient-filters-test.ts
  yarn.lock
Labels: SemVer.Patch

#81 Update publish.yml
  .github/workflows/publish.yml
Labels: SemVer.Patch

#82 Update publish.yml
  .github/workflows/publish.yml
Labels: SemVer.Patch

#83 Update publish.yml
  .github/workflows/publish.yml
Labels: SemVer.Patch

#84 Update publish.yml
  .github/workflows/publish.yml
Labels: SemVer.Patch

#85 Update publish.yml
  .github/workflows/publish.yml
Labels: SemVer.Patch

#86 Update publish.yml
  .github/workflows/publish.yml
Labels: SemVer.Patch

#87 Update publish.yml
  .github/workflows/publish.yml
Labels: SemVer.Patch

#88 Update publish.yml
  .github/workflows/publish.yml
Labels: SemVer.Patch

#90 Fixed base64 encoding issues on web app
  src/apis/impl/MessageGatewayApiImpl.ts
Labels: patch

#91 Release 2.0.5
  src/apis/impl/MessageGatewayApiImpl.ts
Labels: SemVer.Patch

#92 MDT-225 Updated method in DataSample Filter DSL
  src/filter/filterDsl.ts
  test/apis/data-sample-api.ts
  test/apis/user-api.ts
  test/filter/data-sample-filters-tests.ts
Labels: bug

#93 MDT-228 SystemMetadata was not mapped in DataSample model
  src/apis/impl/DataSampleApiImpl.ts
  src/models/DataSample.ts
  test/apis/data-sample-api.ts
Labels: bug

#94 2.0.6 Release
  src/apis/AuthenticationApi.ts
  src/apis/MessageGatewayApi.ts
  src/apis/impl/AuthenticationApiImpl.ts
  src/apis/impl/DataSampleApiImpl.ts
  src/apis/impl/MessageGatewayApiImpl.ts
  src/filter/filterDsl.ts
  src/models/DataSample.ts
  test/apis/data-sample-api.ts
  test/apis/user-api.ts
  test/filter/data-sample-filters-tests.ts
  test/test-utils.ts
Labels: SemVer.Patch
